# Generated by Django 4.2.16 on 2024-11-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_is_approved_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('captain', 'Captain'), ('crew', 'Crew'), ('project_admin', 'Project Admin')], default='crew', max_length=15),
        ),
    ]
