# Generated by Django 4.2.16 on 2024-11-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('captain', 'Captain'), ('crew', 'Crew'), ('administrator', 'Administrator')], default='crew', max_length=15),
        ),
    ]
