# Generated by Django 4.2.16 on 2024-11-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Designates whether a user should be treated as active. Unselect this instead of deleting accounts.'),
        ),
    ]
