# Generated by Django 4.2.16 on 2024-12-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Email address is required and must be unique.', max_length=254, unique=True),
        ),
    ]
