# Generated by Django 4.2.16 on 2024-11-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crewbooking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crewbooking',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('pending', 'Pending'), ('declined', 'Declined')], max_length=10),
        ),
    ]
