# Generated by Django 4.2.16 on 2024-11-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crewbooking', '0002_alter_crewbooking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crewbooking',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('pending', 'Pending'), ('declined', 'Declined')], default='pending', max_length=10),
        ),
    ]
