# Generated by Django 4.2.16 on 2024-11-07 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name of the trip', max_length=100)),
                ('location', models.CharField(help_text='Location where the trip will take place', max_length=100)),
                ('date', models.DateField(help_text='Date of the trip')),
                ('duration', models.PositiveIntegerField(help_text='Duration of the trip in hours')),
                ('crew_needed', models.PositiveIntegerField(help_text='Number of crew members needed')),
                ('captain', models.ForeignKey(help_text='Captain organizing the trip', limit_choices_to={'role': 'Captain'}, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
