# Generated by Django 4.2.16 on 2024-11-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_alter_trip_captain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='location',
            new_name='departing_from',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='date',
            new_name='departure_date',
        ),
        migrations.AddField(
            model_name='trip',
            name='arriving_at',
            field=models.CharField(default=0.0006737333812432626, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='boat_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='boat_name',
            field=models.CharField(default='boaty', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
